---
apiVersion: psengineering.io/v1alpha1
kind: K8sClaim
metadata:
 name: xeks-gitops
spec:
  id: xeks-gitops
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    ## valid values - small, medium, large
    nodeSize: small
    minNodeCount: 1
